import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shred/Navbar/Navbar";
import Footer from "@/component/shred/Footer/Footer";
import { Hind_Siliguri } from 'next/font/google'

const hindSiliguri = Hind_Siliguri({
  weight: ['400', '700'],
  subsets: ['bengali'],
  variable: '--font-bengali',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "I News 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${hindSiliguri.variable}`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
