import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shred/Navbar/Navbar";
import Footer from "@/component/shred/Footer/Footer";
import { Hind_Siliguri, Noto_Serif_Bengali } from "next/font/google";
import { AuthProvider } from "./Context/AuthContext";

const hindSiliguri = Hind_Siliguri({
  weight: ['400', '600', '700'],
  subsets: ['bengali'],
  variable: '--font-bengali-body',
  display: "swap",
});

const notoSerif = Noto_Serif_Bengali({
  weight: ['600', '700'],
  subsets: ['bengali'],
  variable: '--font-bengali-heading',
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "I News 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <AuthProvider>
       <body
        className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} ${notoSerif.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
     </AuthProvider>
    </html>
  );
}